apiVersion: batch/v1
kind: Job
metadata:
  name: ci-test
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: backend-test
          image: backend:latest
          imagePullPolicy: Never
          args: ["nox", "-s", "test:ci"]
        - name: frontend-test
          image: frontend:latest
          imagePullPolicy: Never
          args: ["yarn", "run", "test:ci"]
      restartPolicy: Never
